services:
  redis:
    image: redis:7-alpine
    container_name: redis_broker
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped
    env_file:
      - .env

volumes:
  redis_data: